version: '3.7'

services:


    webgoat:

        container_name: webgoat
        image: webgoat/webgoat-8.0
        ports: 
            - 8080:8080
    
    dvwap:

        container_name: dvwap
        image: vulnerables/web-dvwa
        ports: 
            - 8081:80
    
    
    bwapp:

        container_name: bwapp
        image: feltsecure/owasp-bwapp
        ports: 
            - 8082:80
    
    shop:

        container_name: juiceshop
        image: bkimminich/juice-shop
        ports: 
            - 8083:3000